### ISSUE TITLE
WordPress 

### ISSUE THREAD

**Issue by keme787** [le-yo/mpesa#1]
Hi sorry to put this here but i wanted to know if if this can be used as a woocommerce payment plugin at its current form

**Comment by le-yo** [comment]
Hi @keme787 , this is ready with Laravel 5.

Unfortunately this cannot be used with Woocomerce at the moment. But you can put it as a request and if it gets enough votes we can implement.

**Comment by keme787** [comment]
ok thanks for letting me know
